In [1]:
!pip install sklearn
import pandas as pd 
import numpy as np 
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
from sklearn.datasets import load_boston
boston = load_boston()
print(boston)

{'data': array([[6.3200e-03, 1.8000e+01, 2.3100e+00, ..., 1.5300e+01, 3.9690e+02,
        4.9800e+00],
       [2.7310e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9690e+02,
        9.1400e+00],
       [2.7290e-02, 0.0000e+00, 7.0700e+00, ..., 1.7800e+01, 3.9283e+02,
        4.0300e+00],
       ...,
       [6.0760e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        5.6400e+00],
       [1.0959e-01, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9345e+02,
        6.4800e+00],
       [4.7410e-02, 0.0000e+00, 1.1930e+01, ..., 2.1000e+01, 3.9690e+02,
        7.8800e+00]]), 'target': array([24. , 21.6, 34.7, 33.4, 36.2, 28.7, 22.9, 27.1, 16.5, 18.9, 15. ,
       18.9, 21.7, 20.4, 18.2, 19.9, 23.1, 17.5, 20.2, 18.2, 13.6, 19.6,
       15.2, 14.5, 15.6, 13.9, 16.6, 14.8, 18.4, 21. , 12.7, 14.5, 13.2,
       13.1, 13.5, 18.9, 20. , 21. , 24.7, 30.8, 34.9, 26.6, 25.3, 24.7,
       21.2, 19.3, 20. , 16.6, 14.4, 19.4, 19.7, 20.5, 25. , 23.4, 18.9,
       35.4, 24.7, 31.6, 23.3, 19.6, 1

In [3]:
df_x = pd.DataFrame(boston.data, columns=boston.feature_names)
df_y = pd.DataFrame(boston.target)

In [4]:
df_x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [5]:
print(boston.DESCR)

.. _boston_dataset:

Boston house prices dataset
---------------------------

**Data Set Characteristics:**  

    :Number of Instances: 506 

    :Number of Attributes: 13 numeric/categorical predictive. Median Value (attribute 14) is usually the target.

    :Attribute Information (in order):
        - CRIM     per capita crime rate by town
        - ZN       proportion of residential land zoned for lots over 25,000 sq.ft.
        - INDUS    proportion of non-retail business acres per town
        - CHAS     Charles River dummy variable (= 1 if tract bounds river; 0 otherwise)
        - NOX      nitric oxides concentration (parts per 10 million)
        - RM       average number of rooms per dwelling
        - AGE      proportion of owner-occupied units built prior to 1940
        - DIS      weighted distances to five Boston employment centres
        - RAD      index of accessibility to radial highways
        - TAX      full-value property-tax rate per $10,000
        - PTRATIO  pu

In [6]:
# Initializing the Linear Regression
reg = linear_model.LinearRegression()

In [7]:
# Data = %67 training , %33 test
x_train, x_test, y_train , y_test = train_test_split(df_x, df_y, test_size = 0.33, random_state = 42)

In [8]:
# Training the data
reg.fit(x_train,y_train)

LinearRegression()

In [9]:
# Predict the values from x_test
y_pred = reg.predict(x_test)

In [10]:
# Prediction Values
y_pred

array([[28.53469469],
       [36.6187006 ],
       [15.63751079],
       [25.5014496 ],
       [18.7096734 ],
       [23.16471591],
       [17.31011035],
       [14.07736367],
       [23.01064388],
       [20.54223482],
       [24.91632351],
       [18.41098052],
       [-6.52079687],
       [21.83372604],
       [19.14903064],
       [26.0587322 ],
       [20.30232625],
       [ 5.74943567],
       [40.33137811],
       [17.45791446],
       [27.47486665],
       [30.2170757 ],
       [10.80555625],
       [23.87721728],
       [17.99492211],
       [16.02608791],
       [23.268288  ],
       [14.36825207],
       [22.38116971],
       [19.3092068 ],
       [22.17284576],
       [25.05925441],
       [25.13780726],
       [18.46730198],
       [16.60405712],
       [17.46564046],
       [30.71367733],
       [20.05106788],
       [23.9897768 ],
       [24.94322408],
       [13.97945355],
       [31.64706967],
       [42.48057206],
       [17.70042814],
       [26.92507869],
       [17

In [11]:
# Actual values for x_test
y_test

0
173  23.6
274  32.4
491  13.6
72   22.8
452  16.1
..    ...
110  21.7
321  23.1
265  22.8
29   21.0
262  48.8

[167 rows x 1 columns]

In [12]:
x_test

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS   RAD    TAX  \
173  0.09178   0.0   4.05   0.0  0.510  6.416  84.1  2.6463   5.0  296.0   
274  0.05644  40.0   6.41   1.0  0.447  6.758  32.9  4.0776   4.0  254.0   
491  0.10574   0.0  27.74   0.0  0.609  5.983  98.8  1.8681   4.0  711.0   
72   0.09164   0.0  10.81   0.0  0.413  6.065   7.8  5.2873   4.0  305.0   
452  5.09017   0.0  18.10   0.0  0.713  6.297  91.8  2.3682  24.0  666.0   
..       ...   ...    ...   ...    ...    ...   ...     ...   ...    ...   
110  0.10793   0.0   8.56   0.0  0.520  6.195  54.4  2.7778   5.0  384.0   
321  0.18159   0.0   7.38   0.0  0.493  6.376  54.3  4.5404   5.0  287.0   
265  0.76162  20.0   3.97   0.0  0.647  5.560  62.8  1.9865   5.0  264.0   
29   1.00245   0.0   8.14   0.0  0.538  6.674  87.3  4.2390   4.0  307.0   
262  0.52014  20.0   3.97   0.0  0.647  8.398  91.5  2.2885   5.0  264.0   

     PTRATIO       B  LSTAT  
173     16.6  395.50   9.04  
274     17.6  396.90   3.53  
491     20.1  390.11  18.07  
72      19.2  390.91   5.52  
452     20.2  385.09  17.27  
..       ...     ...    ...  
110     20.9  393.49  13.00  
321     19.6  396.90   6.87  
265     13.0  392.40  10.45  
29      21.0  380.23  11.98  
262     13.0  386.86   5.91  

[167 rows x 13 columns]

In [13]:
# Model Performance
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

20.72402343733979


In [35]:
reg.score(y_test,y_pred)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 13 is different from 1)

In [14]:
df_x

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...    ...   
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.1  2.4786  1.0  273.0   
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.7  2.2875  1.0  273.0   
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.0  2.1675  1.0  273.0   
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.3  2.3889  1.0  273.0   
505  0.04741   0.0  11.93   0.0  0.573  6.030  80.8  2.5050  1.0  273.0   

     PTRATIO       B  LSTAT  
0       15.3  396.90   4.98  
1       17.8  396.90   9.14  
2       17.8  392.83   4.03  
3       18.7  394.63   2.94  
4       18.7  396.90   5.33  
..       ...     ...    ...  
501     21.0  391.99   9.67  
502     21.0  396.90   9.08  
503     21.0  396.90   5.64  
504     21.0  393.45   6.48  
505     21.0  396.90   7.88  

[506 rows x 13 columns]

In [15]:
y_pred1 = reg.predict([[0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1.0,296.0,15.3,396.90,4.98]])

In [16]:
print(y_pred1)

[[29.99003492]]


In [17]:
df_x = pd.DataFrame(boston.data)
df_y = pd.DataFrame(boston.target)

In [18]:
print(df_x)

           0     1      2    3      4      5     6       7    8      9    10  \
0    0.00632  18.0   2.31  0.0  0.538  6.575  65.2  4.0900  1.0  296.0  15.3   
1    0.02731   0.0   7.07  0.0  0.469  6.421  78.9  4.9671  2.0  242.0  17.8   
2    0.02729   0.0   7.07  0.0  0.469  7.185  61.1  4.9671  2.0  242.0  17.8   
3    0.03237   0.0   2.18  0.0  0.458  6.998  45.8  6.0622  3.0  222.0  18.7   
4    0.06905   0.0   2.18  0.0  0.458  7.147  54.2  6.0622  3.0  222.0  18.7   
..       ...   ...    ...  ...    ...    ...   ...     ...  ...    ...   ...   
501  0.06263   0.0  11.93  0.0  0.573  6.593  69.1  2.4786  1.0  273.0  21.0   
502  0.04527   0.0  11.93  0.0  0.573  6.120  76.7  2.2875  1.0  273.0  21.0   
503  0.06076   0.0  11.93  0.0  0.573  6.976  91.0  2.1675  1.0  273.0  21.0   
504  0.10959   0.0  11.93  0.0  0.573  6.794  89.3  2.3889  1.0  273.0  21.0   
505  0.04741   0.0  11.93  0.0  0.573  6.030  80.8  2.5050  1.0  273.0  21.0   

         11    12  
0    396.90  4.98  

In [19]:
df_x_new = df_x.iloc[:,[5,10,12]]

In [20]:
print(df_x_new)

        5     10    12
0    6.575  15.3  4.98
1    6.421  17.8  9.14
2    7.185  17.8  4.03
3    6.998  18.7  2.94
4    7.147  18.7  5.33
..     ...   ...   ...
501  6.593  21.0  9.67
502  6.120  21.0  9.08
503  6.976  21.0  5.64
504  6.794  21.0  6.48
505  6.030  21.0  7.88

[506 rows x 3 columns]


In [21]:
reg_new = linear_model.LinearRegression()

In [22]:
x_train, x_test, y_train , y_test = train_test_split(df_x_new, df_y, test_size = 0.33, random_state = 42)

In [23]:
reg_new.fit(x_train,y_train)

LinearRegression()

In [24]:
y_pred = reg_new.predict(x_test)

In [25]:
print(x_test)

        5     10     12
173  6.416  16.6   9.04
274  6.758  17.6   3.53
491  5.983  20.1  18.07
72   6.065  19.2   5.52
452  6.297  20.2  17.27
..     ...   ...    ...
110  6.195  20.9  13.00
321  6.376  19.6   6.87
265  5.560  13.0  10.45
29   6.674  21.0  11.98
262  8.398  13.0   5.91

[167 rows x 3 columns]


In [26]:
print(y_pred)

[[26.88634969]
 [30.88154954]
 [16.50653608]
 [25.30619008]
 [18.26692404]
 [22.71098092]
 [17.49938745]
 [12.66757083]
 [20.66505072]
 [19.75226425]
 [19.61584853]
 [21.36992145]
 [-1.47096439]
 [22.2816157 ]
 [19.61776413]
 [24.64908506]
 [17.21001254]
 [ 3.97922458]
 [38.77809022]
 [17.25703281]
 [25.91920324]
 [27.45030883]
 [11.8013435 ]
 [23.51264167]
 [17.97051031]
 [13.97690106]
 [22.717485  ]
 [19.24756848]
 [18.17598074]
 [18.88658181]
 [19.7843134 ]
 [25.49649396]
 [24.99843446]
 [18.55980918]
 [14.5193416 ]
 [21.32362182]
 [32.24940954]
 [20.98827864]
 [20.22193499]
 [24.84786219]
 [12.83465254]
 [28.14515184]
 [39.26404338]
 [18.89649761]
 [26.00788822]
 [15.84234976]
 [14.34958264]
 [26.09243894]
 [18.30496336]
 [31.16572851]
 [23.7346402 ]
 [33.44296358]
 [16.02802586]
 [25.63351969]
 [38.10661572]
 [22.42453009]
 [18.34603151]
 [30.08413767]
 [24.79436945]
 [15.48816239]
 [25.45538405]
 [31.96336315]
 [30.02164998]
 [17.36582256]
 [28.31227106]
 [11.95473738]
 [19.11024

In [27]:
print(y_test)

        0
173  23.6
274  32.4
491  13.6
72   22.8
452  16.1
..    ...
110  21.7
321  23.1
265  22.8
29   21.0
262  48.8

[167 rows x 1 columns]


In [28]:
# Seller 1 Prediction
y_pred_seller1 = reg_new.predict([[5,20,19]])
y_pred_seller1

array([[11.77701851]])

In [29]:
# Seller 2 Prediction
y_pred_seller2 = reg_new.predict([[9,10,8]])
y_pred_seller2

array([[44.31281814]])

In [34]:
print(y_test)

        0
173  23.6
274  32.4
491  13.6
72   22.8
452  16.1
..    ...
110  21.7
321  23.1
265  22.8
29   21.0
262  48.8

[167 rows x 1 columns]


In [30]:
# Seller 3 Prediction
y_pred_seller3 = reg_new.predict([[4,30,37]])
y_pred_seller3

array([[-12.08341141]])

In [31]:
from sklearn import metrics
print("Accuracy:",metrics.accuracy_score(y_test, y_pred))

ValueError: continuous is not supported

In [32]:
reg_new.score(y_test,y_pred)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 1)

In [33]:
# Model Performance
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,y_pred))

24.98372270187489
